version: "3.8"

services:
  app:
    depends_on:
      - mysqldb
    build: .
    restart: on-failure
    networks:
      - springboot-mysql-network
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/datacentric_db?allowPublicKeyRetrieval=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.datasource.driver-class-name": "com.mysql.cj.jdbc.Driver"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true


  mysqldb:
    image: mysql:8.0.33
    restart: unless-stopped

    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=datacentric_db
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      retries: 10
      interval: 3s
      timeout: 30s
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - springboot-mysql-network




volumes:
  mysql-data:


networks:
  springboot-mysql-network:
    name: springboot-mysql-network
    driver: bridge